[help]
url = "https://github.com/opto-sync/opto-sync-api-server.rs"

[parse]
allow_unknown = false

[flags.bind]
env = "OPTO_SYNC_API_BIND"
aliases = ["bind"]
type = "string"
default = "127.0.0.1:8080"
help = "HTTP bind address."

[flags.tcp-bind]
env = "OPTO_SYNC_API_TCP_BIND"
aliases = ["tcp-bind"]
type = "string"
help = "Optional stateful TCP bind address."

[flags.nats-url]
env = "OPTO_SYNC_NATS_URL"
aliases = ["nats-url"]
type = "string"
help = "Optional NATS URL."
